name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image from Docker Hub
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/email-service:latest

    - name: Run Docker container
      run: docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/email-service:latest
